#!/usr/bin/env sh
. "$(dirname "$0")/husky.sh"

commit_msg_file="$1"
echo "commit msg file path : $1"
if [ -z "$commit_msg_file" ]; then
    echo  "No commit msg file path"
    exit 1
fi

if [ ! -f "$commit_msg_file" ]; then
    echo  "File not found"
    exit 1
fi

commit_msg=$(cat "$commit_msg_file")
regex="^[A-Z]\+-[0-9]\+: .\+"

echo "Commit msg is: $commit_msg"

if echo "$commit_msg" | grep -qE "$regex"; then
    echo "Commit message passed"
    exit 1
else 
    echo "Invalid commit message"
    echo 1
fi